# Generated by Django 3.2.5 on 2021-07-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_category_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
