# Generated by Django 3.2.5 on 2021-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_courier_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=20),
        ),
    ]
